<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Supplier</name>
   <tag></tag>
   <elementGuidId>cc37de58-959d-4a5f-acce-daf149ca2448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-supplier_id-er-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-supplier_id-er-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-supplier_id-er-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4a174ff3-dca2-474f-b2b4-268f268367aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>151c9adc-cf37-4a70-8256-9075876b5bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-supplier_id-er-container</value>
      <webElementGuid>119bf308-43e6-441c-ab3a-6ad59cdc898d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select option</value>
      <webElementGuid>92f8fb31-9ef1-497b-9791-ea18999d7f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-supplier_id-er-container&quot;)</value>
      <webElementGuid>bf9906f3-1a03-401f-a782-30c7c6531e2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-supplier_id-er-container']</value>
      <webElementGuid>dc109396-b8c7-41e7-b833-9231cbe860bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insert_product']/div/div[5]/div[3]/div/div/span/span/span/span</value>
      <webElementGuid>b08e609f-836d-4e8b-80c5-4e0beddbfbaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[4]</value>
      <webElementGuid>b4c65fed-2b75-4394-9885-e1821c7784ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span/span/span/span</value>
      <webElementGuid>5d57b17a-91cf-4dc5-8526-c909ff09874c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-supplier_id-er-container' and (text() = 'Select option' or . = 'Select option')]</value>
      <webElementGuid>33651107-bc54-4351-bf61-c1a644e87001</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
