<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__UnitName</name>
   <tag></tag>
   <elementGuidId>d197c685-a356-4e26-9545-3b72323611cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unit_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unit_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Unit Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0ddf1c3-1164-4855-8cb1-ed6ee0727f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>daa76120-18ee-40b6-ac7c-4259c6a88fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unit_name</value>
      <webElementGuid>0798d99c-95ab-44ed-b479-f380fdb5d48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>97ee2de7-fa89-4a2c-84e5-e8315c5887ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unit_name</value>
      <webElementGuid>90bd19c4-f866-4b77-ae8a-ab113876ae17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Unit Name</value>
      <webElementGuid>ad6c3aa9-5150-4aeb-9de8-398239a4c1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unit_name&quot;)</value>
      <webElementGuid>c80949a4-ed96-45f7-bb2e-42a547169b8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unit_name']</value>
      <webElementGuid>e788b685-bd95-4fb2-b776-617f510dc51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='unit_form']/div/div/input</value>
      <webElementGuid>af235ec8-62b7-42e1-9dbd-fdaeebb3497b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>b11ab3fb-ad97-4b49-be33-a91f43dc4523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'unit_name' and @id = 'unit_name' and @placeholder = 'Unit Name']</value>
      <webElementGuid>07a22159-c183-4b84-b293-5e29a43556d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
