<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Product</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8a32a761-2cb0-4230-935d-a4a77d606174</testSuiteGuid>
   <testCaseLink>
      <guid>16c94eac-3fa7-4959-9f4d-f63b891e1edd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HA/TC_001_AddCategory</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a886b30-c2b3-4934-bea6-eed77b2512f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d51ecaa0-3a53-4d24-b3cd-ffbb9ee9f596</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba60d6f5-deb1-497e-b9b7-57d12b742a58</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27afcc73-f8be-4c43-999d-c2d27f4bd756</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HA/TC_002_EditCategory</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8202868-0daf-4de6-8114-6f1ad0ee8c1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44a56913-2f5c-4b6e-a508-4e4de02235ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d88b098-1048-497b-a36b-756ca4dbfec7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>352efe32-5470-4e78-8ef1-3985f0f612c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HA/TC_003_DeleteCategory</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>990424df-7c21-4e68-9939-b333e20dfd98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b048bfec-48ed-401d-a7bf-fbecfc4f5f91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>480c2ff8-c8c6-4b83-ab5e-344e985e999e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0df95e8a-3c67-4303-9e3e-8b2d5e5d9b1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HA/TC_004_AddUnit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f477fdcb-de3f-412c-989e-8b0dcdde49bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7e39170-d311-4730-8ba5-913226e11583</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>423d9823-93c5-4b22-b84a-10563ee5b8f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e4d2ff0-9824-47cb-a37a-6b2c8f5b3051</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HA/TC_005_EditUnit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5de18e27-9fc0-429e-b4eb-74b5808bb497</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87308e7c-edb9-4878-8b45-cc7f9f099e30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c722bd13-2b0a-401b-a8b7-db1f8e66820d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>46d0f976-a481-4652-82ef-61fc02dcfb71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HA/TC_006_DeleteUnit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebf5aef4-e909-4c76-8ff9-8c4d32c87016</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6047ea0-9fc9-4f48-90cd-55f81136c18f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88731856-748b-4549-b645-bd689b93b9d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90edf1f3-fc67-4021-8a2d-ba616e62ee80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HA/TC_007_AddProduct</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8dfe9314-cfe9-447d-92e3-e59df4cbc3de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04925a49-164c-47fc-957a-ce388889777b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1e9ebd1-3408-41eb-8ec9-413ca9fa9819</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71117860-fad2-4ead-a8ec-b3dd450f2a09</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e678d50-2379-46e9-a003-f0f1a6063d74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HA/TC_008_EditProduct</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76cc9ab3-9a92-48ee-9a59-9920c0bd2026</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15a750f0-701f-48fe-8594-999906df6a46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0777152-563c-426d-aee3-5e1bcce604a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ceb44027-8362-4a10-b1a1-90a71ce7437d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2aaf113-a42a-4567-9eea-435419bb2b2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HA/TC_009_DeleteProduct</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4899ea0b-525d-48ba-9cf4-a474cde703e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5be940b6-fa1b-4aa4-9bfb-0139eaec2aac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f329e59d-d9c6-41fe-9f6a-bae1b0dcca64</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
