<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Active_btn btn-info btn-sm</name>
   <tag></tag>
   <elementGuidId>520deb2a-07c6-4b6c-990d-36c08af48d25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-info.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='dataTableExample3']/tbody/tr/td[4]/center/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Update&quot;i] >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>816469bf-0296-4b06-a91e-391ecef489e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://saleserpdemo.bdtask-demo.com/v10_demo/category_form/2</value>
      <webElementGuid>99b9bae4-9890-487c-b6ee-5a9532158e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-sm</value>
      <webElementGuid>7c30d89d-4342-4414-82b3-4ac922881cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>4dba6d66-335c-4f6e-bc9f-2b79b353b9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>54fc04aa-79d3-4604-b631-0a043c200fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>077aa82d-0058-4084-8ab1-959590cfd5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip646126</value>
      <webElementGuid>8faa7296-3ab9-4516-877b-15dc545dc43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataTableExample3&quot;)/tbody[1]/tr[1]/td[4]/center[1]/a[@class=&quot;btn btn-info btn-sm&quot;]</value>
      <webElementGuid>0e694cc3-deea-46a7-88e3-c025306876db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dataTableExample3']/tbody/tr/td[4]/center/a</value>
      <webElementGuid>d5ecb84e-7174-45d8-b280-8cae7cd3b245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::a[1]</value>
      <webElementGuid>5647b7aa-e85f-4a9a-a791-3cd44214aa5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crockeries'])[1]/following::a[1]</value>
      <webElementGuid>12aaa9b4-0373-45ea-8ce3-637a9fa8745b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[1]/preceding::a[1]</value>
      <webElementGuid>d5660712-7b4b-4b64-92eb-6b319ada9f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chocolate'])[1]/preceding::a[2]</value>
      <webElementGuid>da57d19a-8e88-4ea3-9371-9f84c8e2e7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://saleserpdemo.bdtask-demo.com/v10_demo/category_form/2')]</value>
      <webElementGuid>17aef350-712e-4be2-8121-5211b6f8102e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/a</value>
      <webElementGuid>c9029105-e3a1-4ea9-9904-a9953235322e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://saleserpdemo.bdtask-demo.com/v10_demo/category_form/2']</value>
      <webElementGuid>6a1f1f01-5ae0-4ec2-b756-278a363b7819</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
