<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CSV</name>
   <tag></tag>
   <elementGuidId>8f533391-8d09-48ec-a6cc-5302efcbe06d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-default.buttons-csv.buttons-html5.btn-sm.prints</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkListStockList_wrapper']/div[4]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=/^CSV$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6ba03407-6a9d-40f2-9183-0056cd03d47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default buttons-csv buttons-html5 btn-sm prints</value>
      <webElementGuid>a2d7b795-460a-49c3-8431-0131f1cf705c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3800532b-0224-4d43-9d39-d9b62cb61ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>checkListStockList</value>
      <webElementGuid>aa042c66-0ce8-4074-8025-614fd1bb1103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CSV</value>
      <webElementGuid>8e4e92f7-398d-4904-b9bb-d81f6d9d0657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkListStockList_wrapper&quot;)/div[@class=&quot;dt-buttons btn-group&quot;]/a[@class=&quot;btn btn-default buttons-csv buttons-html5 btn-sm prints&quot;]</value>
      <webElementGuid>944ce6d1-e5ef-48e5-9f53-49b76102e370</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkListStockList_wrapper']/div[4]/a[2]</value>
      <webElementGuid>f34b2a82-5e69-405f-a7af-390d5763dfd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[1]/following::a[1]</value>
      <webElementGuid>d8803751-d74e-4663-b329-a6ff8def207e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excel'])[1]/preceding::a[1]</value>
      <webElementGuid>8fd27428-5d3b-44d6-939a-19989b8ccc51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a[2]</value>
      <webElementGuid>60efabd2-51a8-4f3a-b34f-ee14d32ab23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'CSV' or . = 'CSV')]</value>
      <webElementGuid>3d198aa6-b5a0-4ada-8345-294d7f3c6eb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
