<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Excel</name>
   <tag></tag>
   <elementGuidId>b8f894ab-c0f0-4ad0-9494-01159244dda6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-default.buttons-excel.buttons-html5.btn-sm.prints</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkListStockList_wrapper']/div[4]/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;Excel&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1e1cf035-4a14-4201-b66f-b2acc3bcc50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default buttons-excel buttons-html5 btn-sm prints</value>
      <webElementGuid>8e82a61f-c3d1-44ab-9a04-fb66b88f82e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d6c12b66-af6b-4ef8-a7f9-18eb03f767e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>checkListStockList</value>
      <webElementGuid>387f2f3d-dbe2-4137-9b1f-e0b4de24797c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Excel</value>
      <webElementGuid>99edd8df-64b0-4ec5-8ef0-4ee3bc72a2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkListStockList_wrapper&quot;)/div[@class=&quot;dt-buttons btn-group&quot;]/a[@class=&quot;btn btn-default buttons-excel buttons-html5 btn-sm prints&quot;]</value>
      <webElementGuid>e208bd3e-c991-4535-9173-bd907e68c965</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkListStockList_wrapper']/div[4]/a[3]</value>
      <webElementGuid>45601b45-ffb4-487f-b37b-f01ab83a3b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSV'])[1]/following::a[1]</value>
      <webElementGuid>66a0706e-efe6-43c1-a34b-3fe41b36f0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[1]/following::a[2]</value>
      <webElementGuid>ae68a31b-d6a5-429d-b13e-c0a1c606fa32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF'])[1]/preceding::a[1]</value>
      <webElementGuid>eef95ffc-1436-4534-b0da-ce6d307ec13a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a[3]</value>
      <webElementGuid>93b4ece5-ba44-4803-b6cc-89f989741a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Excel' or . = 'Excel')]</value>
      <webElementGuid>83a84fce-efef-436b-ace8-0df8610eda1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
