<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PDF</name>
   <tag></tag>
   <elementGuidId>f1a884ff-763f-44da-99ca-447fa8afd4b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-default.buttons-pdf.buttons-html5.btn-sm.prints</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkListStockList_wrapper']/div[4]/a[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;PDF&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f36bfc9-dd0f-4f64-91c2-5eb7daab9c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default buttons-pdf buttons-html5 btn-sm prints</value>
      <webElementGuid>bf6d1dfb-954c-4419-943d-f0435fd52fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>70eb717a-b0d8-4809-8d9f-3e3ba97dba44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>checkListStockList</value>
      <webElementGuid>e60a8609-62d3-41af-a863-fe420663f25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PDF</value>
      <webElementGuid>1c4bec71-cc47-4562-a01c-8181101058df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkListStockList_wrapper&quot;)/div[@class=&quot;dt-buttons btn-group&quot;]/a[@class=&quot;btn btn-default buttons-pdf buttons-html5 btn-sm prints&quot;]</value>
      <webElementGuid>7eddae2f-29ec-4159-84df-1e831583137e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkListStockList_wrapper']/div[4]/a[4]</value>
      <webElementGuid>e915c287-a496-4929-89cc-9b51d04d28a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excel'])[1]/following::a[1]</value>
      <webElementGuid>ddcc9ab1-1712-442b-ad5f-4c3ffa72bec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSV'])[1]/following::a[2]</value>
      <webElementGuid>22805bad-957f-480e-817c-60ce2f7fb6c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/preceding::a[1]</value>
      <webElementGuid>6e277885-a8ee-4881-aa78-2b5273024cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a[4]</value>
      <webElementGuid>7cd35e7b-90c3-46c7-aa5a-ad2098a153d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'PDF' or . = 'PDF')]</value>
      <webElementGuid>5978eb76-f898-4f5d-bd96-d49352d865e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
