<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MobileNo</name>
   <tag></tag>
   <elementGuidId>bc0b942f-7dc8-4feb-a775-ed765e39c79f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='supplier_mobile']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#supplier_mobile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22d466a4-55d8-42b7-822d-7c40d0264302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>59e6cbb2-abc1-47fc-812f-99a6e10a20a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>supplier_mobile</value>
      <webElementGuid>5c0d483b-2001-4bcf-bd0e-c8c86643d0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-mask-trigger text-left</value>
      <webElementGuid>a1e8f48b-ef00-4a64-a2c6-669f2cc7ae68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>supplier_mobile</value>
      <webElementGuid>39e56b59-5a0e-44f0-9845-0bde7e65c0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile No</value>
      <webElementGuid>5e8baa4a-207f-444e-b7d4-39d5f813d3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-inputmask</name>
      <type>Main</type>
      <value>'alias': 'decimal', 'groupSeparator': '', 'autoGroup': true</value>
      <webElementGuid>d7092f6c-e71c-44f3-9592-c4897d84a390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>im-insert</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>946cb86c-a1bc-45c7-9d8e-cfd02b605e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supplier_mobile&quot;)</value>
      <webElementGuid>fef7f2b5-aa97-405a-a4c0-c4012a3a2a2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='supplier_mobile']</value>
      <webElementGuid>ede69e92-2d5a-4396-ab32-e8dbd6ea9433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='supplier_form']/div/div[2]/div/input</value>
      <webElementGuid>3a8cdf20-bec0-472c-b4f3-882b49047f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>de32eafd-2b25-44f4-bc1f-3b106dbc8512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'supplier_mobile' and @id = 'supplier_mobile' and @placeholder = 'Mobile No']</value>
      <webElementGuid>0079a2cd-21c8-4cfd-8d85-15457873936b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
