<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address2</name>
   <tag></tag>
   <elementGuidId>8661960b-e34a-47bb-9f79-d064b4dafbbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='address2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>929e89e3-e2cb-4877-8631-9c63b8e98067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address2</value>
      <webElementGuid>6ff81ebe-3639-4c73-ab34-13e84d221f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address2</value>
      <webElementGuid>1e1ee804-6c97-452a-98f6-32e86b388fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>16613bfe-7c71-422a-b70a-3a4547f3244a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address2</value>
      <webElementGuid>7b65dca7-72bc-4ba2-8165-93c339f9dd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address2&quot;)</value>
      <webElementGuid>0a2c7958-d6cb-45f0-a664-e7ebde9f2d9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='address2']</value>
      <webElementGuid>914c716f-0b8d-4dee-a36a-d11d08b6f120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='supplier_form']/div[4]/div[2]/div/textarea</value>
      <webElementGuid>9d05554d-4bb8-4a9c-a275-75e32d2fa5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/textarea</value>
      <webElementGuid>0b38c7c7-4804-4d39-afa4-b42bfa3f6733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'address2' and @id = 'address2' and @placeholder = 'Address2']</value>
      <webElementGuid>9c2f0b13-a757-4636-b534-1a00d224051e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
