<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Grand Total_add-quotation</name>
   <tag></tag>
   <elementGuidId>2a9f5b6e-781f-4071-b0c1-141a089128d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-quotation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add-quotation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06d772f0-9e8f-4296-a1d2-40dd21c9ad6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5a59b2a1-3a81-498f-b7b4-8cefe13da5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-quotation</value>
      <webElementGuid>2f2a2c0e-d0ba-4e0e-9042-8fae6b1430f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-large</value>
      <webElementGuid>b6b95d53-cf1c-4a17-9da5-070726f343cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add-quotation</value>
      <webElementGuid>a0617f0d-d8e1-49ef-8628-6178203264d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>f942d80b-5e0d-4be9-a729-766e737e109b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-quotation&quot;)</value>
      <webElementGuid>7f0facca-aec0-43a7-b4c0-e7301a0e0cf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add-quotation']</value>
      <webElementGuid>fcf33844-1d91-4e37-b724-9a33d6435fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insert_quotation']/div/div[8]/div/input</value>
      <webElementGuid>f9e479fc-abcd-4656-ac43-06d1810457fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>38d03f9b-055d-4c16-a2ac-44302ddb74c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'add-quotation' and @name = 'add-quotation']</value>
      <webElementGuid>f8a9a7f4-9e5a-49f2-9bab-1adebb4efdbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
