<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank Name</name>
   <tag></tag>
   <elementGuidId>e17ad28a-129e-4ce2-9e46-1f89f144b6ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bank_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'bank_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad19b1d8-5fcb-4f52-b7f4-ab2c346fd556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b31a734-7f56-405b-bfde-553e9612fddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>58cb13c1-6c4d-40a3-8dae-cad489ff090e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bank_name</value>
      <webElementGuid>78a25dd0-97db-404d-b704-8329caef6aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bank_name</value>
      <webElementGuid>a5e0fb6b-8b3c-4cb9-aa66-a4cfdb59e1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bank Name</value>
      <webElementGuid>8323770f-a2c0-4619-823e-608474251766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d6c1c5b3-6a87-439b-a5cf-4433b009a91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2a9f458b-519f-4b14-b402-58757c02051b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2131084a75ea45a7325d0249eb2f318a</value>
      <webElementGuid>f17a59c7-3891-4aa3-baa8-ab5c08b9a795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'bank_name']</value>
      <webElementGuid>a5fb74b9-0eac-4491-9749-f869ac4cf3d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'bank_name']</value>
      <webElementGuid>2eb5457c-5fee-47ae-9755-56d6aaebf784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bank_name' and @id = 'bank_name' and @placeholder = 'Bank Name']</value>
      <webElementGuid>f2de07ec-5f4a-4781-a52b-718f3749fe58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
