<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_A_C Name</name>
   <tag></tag>
   <elementGuidId>c56db8ba-48ae-4cc9-8074-7568d4fa9488</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ac_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ac_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e60e8f44-b69f-477d-bd7f-b36866da0847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c5ca7de-4883-4a11-a056-7efb60c514ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c0d551c4-93b6-4e52-94dc-b0600d0f0eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ac_name</value>
      <webElementGuid>609a2709-d7aa-404c-b077-a5a2f697cb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ac_name</value>
      <webElementGuid>1f48a838-91ea-4126-bc67-43be82055f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>A/C Name</value>
      <webElementGuid>60666436-20af-4ee0-83d4-04ed42994f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f0d09d55-e223-44e9-9372-b7c7890b765b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c7234496-8565-4a29-b1c5-3add7320fb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f2732fb62489b5eff87f7bf87bd19645</value>
      <webElementGuid>19cf92d4-e009-49fb-847a-c65931c0b207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ac_name']</value>
      <webElementGuid>3508b37b-7018-4bf1-919b-b90045d9cc29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ac_name']</value>
      <webElementGuid>d8ea7b56-1a0f-4ea5-984c-4676021fe4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ac_name' and @id = 'ac_name' and @placeholder = 'A/C Name']</value>
      <webElementGuid>372ecf3f-4609-473c-b1a6-da6ff91fe25c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
