<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_add-deposit</name>
   <tag></tag>
   <elementGuidId>1f1b9923-7bb7-4948-8200-146234c14f7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-deposit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'add-deposit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef1333d3-d1ee-417f-8958-04393cccadbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1a28348a-06c1-445c-9bbb-ff93e38ea43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-deposit</value>
      <webElementGuid>05111dee-3bd8-40a2-a40d-c10b34d250df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>504c56f7-053d-4090-ae0e-910d5f4d0005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add-deposit</value>
      <webElementGuid>c30083a8-b556-4baf-9f9a-438c3e866b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>5367eb0e-1b0d-4996-b2e9-82b71b668392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>08a37f23-5bf8-4f59-a083-0dd63477580a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-256732abe9cd9c3277f4a8e94efcaa4f</value>
      <webElementGuid>e2c338a3-2988-4dcf-ae79-36cd57c3ce09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'add-deposit']</value>
      <webElementGuid>83593eb3-e71b-4553-a04b-00ee650d91ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'add-deposit']</value>
      <webElementGuid>f6fbb6f9-c933-4c5c-a3be-7ffa7bdba6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'add-deposit' and @name = 'add-deposit']</value>
      <webElementGuid>bf8cc231-3631-4acc-bfec-d325ae8dbfb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
