<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Signature Picture_add-deposit</name>
   <tag></tag>
   <elementGuidId>30b5d1ea-9107-4048-abdb-7131e8305a41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-deposit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add-deposit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7e0ada8-2b03-4601-84d2-dc4dc8376057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4af53cba-e4cb-4d1f-b7bb-7ee744eb17b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-deposit</value>
      <webElementGuid>c5addbde-9992-409e-8c21-92e6954fa165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>c1fbc861-f35d-48ce-9e07-c4346b59efc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add-deposit</value>
      <webElementGuid>4a5aca8a-424a-4c65-b13f-a52c3dc0cae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>1c4f165b-d323-472d-8fe3-b24fc85062d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>0230c876-e961-402f-9a5f-f064acf924d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-deposit&quot;)</value>
      <webElementGuid>88f14b8a-6a0f-417f-9065-a3454d504053</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add-deposit']</value>
      <webElementGuid>1811c53f-8e43-4277-bbc9-7174666a42c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='validate']/div/div[6]/div/input[2]</value>
      <webElementGuid>c1cfc9f9-5f4a-43f5-b243-9fdb8d0b785a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input[2]</value>
      <webElementGuid>0d29e167-fa42-4391-bd0c-10793a7c1bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'add-deposit' and @name = 'add-deposit']</value>
      <webElementGuid>215eb25a-a369-4dc5-ba3e-baee43180e4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
