<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_A_C Number</name>
   <tag></tag>
   <elementGuidId>df7e763c-dcbc-4156-b43d-a7bb6e525c5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ac_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ac_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d8dace1-fdd0-48ac-828a-2a1073757e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8286456f-e417-4722-868a-46ca867d2c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2cee8096-60e4-4ecd-8c69-0c71d924c1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ac_no</value>
      <webElementGuid>078518cf-f681-4e2a-bc48-6ffe05de3cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ac_no</value>
      <webElementGuid>538d48c1-8575-4f52-a410-443e4f0d3195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>A/C Number</value>
      <webElementGuid>5686785d-fd19-4700-93f3-4fd18407e0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b68113cb-8b6f-4730-810a-2da0aaa77c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7def88cb-fa69-4ff0-bdec-06ddf9816e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a19f011270898043fb2b955fbf1a65a3</value>
      <webElementGuid>5ddecb48-4402-4c13-be99-16dcaf4b1b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ac_no']</value>
      <webElementGuid>2b994bb9-bd0f-4c36-8302-7a91ffc1f52e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ac_no']</value>
      <webElementGuid>a97832bd-eb88-43a5-ba19-59e11e10d7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ac_no' and @id = 'ac_no' and @placeholder = 'A/C Number']</value>
      <webElementGuid>09f21610-67c3-4bf1-970a-c9fa1f298595</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
