<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Branch</name>
   <tag></tag>
   <elementGuidId>31112782-3510-4901-965c-73a7df800f29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#branch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'branch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1be6d896-50ab-433b-bf39-15f0e05b46d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b0aa3ee-ad03-47fd-bbc2-e05bc3920cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bfdab3d4-e3ca-498d-bdcc-c2189fde1e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>branch</value>
      <webElementGuid>08a4be90-7c32-4655-9c89-80e6c962637c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch</value>
      <webElementGuid>55d252c3-2413-40c7-a66b-4ea5c47aff45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Branch</value>
      <webElementGuid>8f4a22a3-c876-4231-8bb7-27a30e7ea32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b063be52-fa2a-4f23-8495-f2cdba5d88ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e876cfa9-48b4-4198-8fd2-9d53f9436920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-07bbcfc9014617e9414a09be35b88687</value>
      <webElementGuid>b18b0936-8464-407a-9a1f-45fca9dcb966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'branch']</value>
      <webElementGuid>2532d3f8-c8d4-480c-adf1-4e1798558a32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'branch']</value>
      <webElementGuid>6dc1404c-e79a-4453-869e-8983735a398b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'branch' and @id = 'branch' and @placeholder = 'Branch']</value>
      <webElementGuid>f279b693-bee7-4274-adcc-a3b047b0b910</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
