<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Charge</name>
   <tag></tag>
   <elementGuidId>7c82ebc0-8b64-4cb4-8c88-43194eeddfbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#charge</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'charge']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ee48939-800f-4831-be74-bb94e14ce533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>72c9a74c-0f06-43a5-8ab7-d7aff5ad9e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>charge</value>
      <webElementGuid>e7d762db-6890-4ed8-837c-1385826ffbb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>charge</value>
      <webElementGuid>179ec0c5-93c7-4f7b-bec5-b2c5b914b855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aebfb710-dcce-4cd3-8415-244e1a86de39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Charge</value>
      <webElementGuid>01814e2d-d109-469c-9bbd-0cc7bb4f2d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-299f3581dbd4099a29b1135c1b7dba28</value>
      <webElementGuid>fcf3ab67-4167-4f44-82af-bccf624e38a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'charge']</value>
      <webElementGuid>fa13d9c9-e4b1-4f71-a5c7-2a84209772c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'charge']</value>
      <webElementGuid>b5fa33e4-87fa-474c-92d9-278ad003fd8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'charge' and @id = 'charge' and @type = 'text' and @placeholder = 'Charge']</value>
      <webElementGuid>20030897-3880-4273-88e4-fbcbc07b78b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
