<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_add-service</name>
   <tag></tag>
   <elementGuidId>ad2044fe-2701-43d5-b440-5930d31ef351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-service</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'add-service']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2a71a7d-3bc4-49c1-a0d9-0dd61c267217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f0f8629a-febe-4ed6-9370-38df2d4c4e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-service</value>
      <webElementGuid>85542e8b-444b-4fd8-bf39-93b8b7a79d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-large</value>
      <webElementGuid>626ad51d-250e-4e4d-9ce4-b6b5fa529692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add-service</value>
      <webElementGuid>f15da3ca-835e-49f9-ae63-d1576f1045b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>842989cd-d586-4841-be8d-4349bc5b6ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-003befbbb59ff741c6881f48e5773d2b</value>
      <webElementGuid>2150ff46-9809-46b7-8509-c576a49604cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'add-service']</value>
      <webElementGuid>208943d7-66b4-4eb9-8ed0-3cdeee995134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'add-service']</value>
      <webElementGuid>d52fccc8-569a-4a2f-b12e-5c86da2c6f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'add-service' and @name = 'add-service']</value>
      <webElementGuid>e1a6d9e5-d014-4988-ae8b-4083bf069f71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
