<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_add-service</name>
   <tag></tag>
   <elementGuidId>ad2044fe-2701-43d5-b440-5930d31ef351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-service</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit' and @id = 'add-service' and @name = 'add-service']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'add-service']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6c3c6f6-85c7-4da7-a058-7f8e654df4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fa252d24-9133-430c-83c2-a2c3818e0d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-service</value>
      <webElementGuid>d93a7af4-a253-435d-9aba-3f1c5032f2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-large</value>
      <webElementGuid>07a6cee4-5fe5-47cc-9d8f-96d7ae43ce91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add-service</value>
      <webElementGuid>748c1e81-ebe5-466c-a7aa-d90346a09c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>a79027f7-db10-4010-8ec8-e5b8edf54a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-003befbbb59ff741c6881f48e5773d2b</value>
      <webElementGuid>e24edf0c-adaa-4d6b-8580-11c43d647ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'add-service']</value>
      <webElementGuid>114e88a5-e74b-4fc5-bd06-b5598897b756</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'add-service']</value>
      <webElementGuid>11205220-45b6-48b8-96d6-bf7aa9bf7490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'add-service' and @name = 'add-service']</value>
      <webElementGuid>3c2e371b-4df4-4a69-8f83-6f676f1e80db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
