<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Service VAT _</name>
   <tag></tag>
   <elementGuidId>a79e3bb3-ba67-4254-94eb-e9a4604b6799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#service_vat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'service_vat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d77c3d0f-ac67-4975-a44d-c40c10c9e0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3e381ff1-98e9-44e7-bd3b-2f3e88e76a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>service_vat</value>
      <webElementGuid>d0d24c3f-f689-4d23-8438-f2a258e4c31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>service_vat</value>
      <webElementGuid>8150ad57-aa7e-499f-8aa4-57ab29e8c023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>617f5170-f75e-4ea7-bd87-0adb24a8cefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Service VAT %</value>
      <webElementGuid>2760e441-ddc4-4805-96b3-7a99050e2aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4b91412b36853923221a5499c0af5156</value>
      <webElementGuid>5f7b7458-2dd6-44d3-994b-42542a61007d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'service_vat']</value>
      <webElementGuid>708bc296-3d74-4013-8c8a-215453a7af28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'service_vat']</value>
      <webElementGuid>c62b8e0e-08f1-446e-afcb-aa821ddcb74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'service_vat' and @id = 'service_vat' and @type = 'text' and @placeholder = 'Service VAT %']</value>
      <webElementGuid>f071f3bf-6768-4caa-8d00-cdbad2adb788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
