<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_add-service</name>
   <tag></tag>
   <elementGuidId>3c975f9e-0b7a-4fa0-81a4-8ac8e2e96038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-service</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add-service']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88a1011c-59ba-47dc-b168-71f21a2e0759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e3de9ba8-04d4-474f-9901-a742c6fab8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-service</value>
      <webElementGuid>75d7a736-1722-4f85-b439-797eede69cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-large</value>
      <webElementGuid>20feaa55-717f-45ef-8633-44e435a8b207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add-service</value>
      <webElementGuid>c2ffe596-911d-4818-bd36-c7ba8a752479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>cd5e6066-65ad-4a5b-b3c1-f3258c086c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-service&quot;)</value>
      <webElementGuid>180b96dc-2cfb-4126-89f9-e3a9237af5f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add-service']</value>
      <webElementGuid>320b597d-c7db-4164-bab4-2cac209b838f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insert_service']/div/div[5]/div/input</value>
      <webElementGuid>91d6020b-24be-412b-a8cd-fb24c7c793e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>35156420-031f-4aba-be40-140cc2d200fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'add-service' and @name = 'add-service']</value>
      <webElementGuid>50fc228e-2565-4a81-ac31-6611ee6b735f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
