<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Charge</name>
   <tag></tag>
   <elementGuidId>7c82ebc0-8b64-4cb4-8c88-43194eeddfbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#charge</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'charge' and @id = 'charge' and @type = 'text' and @placeholder = 'Charge']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'charge']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bde3f039-0e5d-4027-83f1-5378007b0760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>96b68c4d-85e4-4c7b-aaa8-5d36ea0ec67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>charge</value>
      <webElementGuid>f735cdaa-1fe8-4295-9d73-2d3e40a3c64d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>charge</value>
      <webElementGuid>c7d170c7-4cdf-497d-936f-dfc300458a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0254e7fa-9e18-415c-b0f9-59510a1c7e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Charge</value>
      <webElementGuid>3f31f9de-20e3-477e-b873-7e97c7c243c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-299f3581dbd4099a29b1135c1b7dba28</value>
      <webElementGuid>9ff81f5f-8f84-4a22-a43b-117aaf218ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'charge']</value>
      <webElementGuid>13951076-8cfd-4bef-a520-0459aceb6e58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'charge']</value>
      <webElementGuid>b3862921-2839-4711-8bd2-115fdc781799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'charge' and @id = 'charge' and @type = 'text' and @placeholder = 'Charge']</value>
      <webElementGuid>f34f6ab7-c816-45e5-aab3-a5f47743ec18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
