<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Service Name</name>
   <tag></tag>
   <elementGuidId>a05d2599-aa0b-4f77-8ccc-a1ac917ac412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#service_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'service_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>691b5d43-28cc-498b-869b-a7f16bc605f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>372822cc-5682-4730-88e5-988fbe490c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>service_name</value>
      <webElementGuid>2f1a29c3-bea5-47e0-ba0d-a1f8032d2ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>service_name</value>
      <webElementGuid>f4155aad-aab2-481b-a51a-e0c1a6309ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>efe98572-9e70-41e2-8f46-cd45227eb8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Service Name</value>
      <webElementGuid>876e0125-5785-4d22-9752-6d958654eee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8840164ffeb4f72bd0a3c7ac097ddd0a</value>
      <webElementGuid>42ef88a3-1543-46ce-a3ca-9314dfee3c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'service_name']</value>
      <webElementGuid>627bd7f9-3030-44c4-a301-c1c36767784f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'service_name']</value>
      <webElementGuid>563e6715-2319-45ca-a22c-aafd438a8d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'service_name' and @id = 'service_name' and @type = 'text' and @placeholder = 'Service Name']</value>
      <webElementGuid>731f1f7a-aaae-4417-a991-a4ac9d46b37c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
