<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_add-deposit</name>
   <tag></tag>
   <elementGuidId>dbe7860f-d29e-487a-a9ef-f4da40e7f2b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-deposit</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit' and @id = 'add-deposit' and @name = 'add-deposit']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'add-deposit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbda72e2-8aa5-4329-9561-258a1f408189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b628777f-18a8-4334-a54f-f53d54234cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-deposit</value>
      <webElementGuid>08d65bfe-d2dd-4637-8717-996deb07792c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>e58fa427-99d0-494b-8dd8-adff402575fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add-deposit</value>
      <webElementGuid>a5c260b9-e2a5-4024-985c-e9145144ebd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>b6b0dc91-d612-40ec-a086-b72edd6df585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>66c1d752-8af9-4022-bffe-0d491a33739a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-256732abe9cd9c3277f4a8e94efcaa4f</value>
      <webElementGuid>ba79fefb-b78a-409e-afa8-1f1503abc4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'add-deposit']</value>
      <webElementGuid>c35f6f19-3cb0-4d60-930a-f1cb20cf0f10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'add-deposit']</value>
      <webElementGuid>001eade8-a5cd-459d-a38f-2e3b6e0dea5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'add-deposit' and @name = 'add-deposit']</value>
      <webElementGuid>7bbbac29-e034-44cb-be48-76d5ca507497</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
