<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cost Price_cost_price</name>
   <tag></tag>
   <elementGuidId>5337e340-0e5e-4290-ac95-ce7da649e04c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cost_price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cost_price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cost Price&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d78d9dc3-2945-46b9-b515-2ba9163be1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-right</value>
      <webElementGuid>3b1bf631-8abd-4be8-aa7e-4f860364f34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cost_price</value>
      <webElementGuid>05f69e54-c765-41e2-83ca-caa7213760da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>supplier_price</value>
      <webElementGuid>d52fa6f3-ac5d-40ca-a47b-1f502bff8aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e408fb5f-818c-4e44-a907-d9585658d2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>f0b3b864-c3c0-4b0c-87ce-17e0f401970b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5674e052-2470-40d5-9b3d-ade303719cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f1fa74da-99f7-4107-9e71-1abfb7061fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cost_price&quot;)</value>
      <webElementGuid>9510501d-c02f-4a03-81a1-ddb2f451b2b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cost_price']</value>
      <webElementGuid>e0b977ab-34ba-44fb-9fb3-fea9c6b98d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insert_product']/div/div[4]/div[3]/div/div/input</value>
      <webElementGuid>9c32e4cd-d1dd-4ff3-b4aa-6144af5a9619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>974da33e-4295-4093-87f2-f82664f8df0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cost_price' and @name = 'supplier_price' and @type = 'text' and @placeholder = '0.00']</value>
      <webElementGuid>3b92c02d-75a1-4cf8-a5c6-a14d4093c8f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
