<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Product VAT_product_vat</name>
   <tag></tag>
   <elementGuidId>9c2fd299-cb09-4448-b70c-51f50a77c358</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_vat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_vat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Product VAT %&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17225003-bf78-418c-8a06-32aac1a6c728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0e062496-3d28-4183-b4f5-fa89fea179fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>690bd5ea-ced4-4234-930e-3ebd6839f8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_vat</value>
      <webElementGuid>1752a2f1-f4df-421b-be57-a8d9be52d37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_vat</value>
      <webElementGuid>49a11540-aab0-4248-8ce8-9fc1ba944c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Product VAT %</value>
      <webElementGuid>29cb8a85-3c25-4757-ae5c-bb30d7518b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_vat&quot;)</value>
      <webElementGuid>a49ee782-d1f5-4af2-bd22-a0f184ad1ef6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_vat']</value>
      <webElementGuid>776cac22-eb71-433e-8651-8acdfd8dbeb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insert_product']/div/div[5]/div[2]/div/div/input</value>
      <webElementGuid>9777aa3b-98b1-4505-b744-f05d64c6d08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>f9f458ec-2021-4d6b-b5c1-f332b9e65399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'product_vat' and @name = 'product_vat' and @placeholder = 'Product VAT %']</value>
      <webElementGuid>406c05d1-9d62-4bbc-a13a-f7798c04fbbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
