<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SN_serial_no</name>
   <tag></tag>
   <elementGuidId>35b1c613-aa00-4c98-beac-511af53e59a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#serial_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='serial_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;111,abc,XYz&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b9ac441-9fa7-411b-8265-93d7a2ffa6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ede690d-5856-4791-9819-73147bf49cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>b58c1705-2002-4914-99f4-db4eb2bbe869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serial_no</value>
      <webElementGuid>de3fa456-e1e8-4384-9a55-04bc0f770864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>serial_no</value>
      <webElementGuid>3e56709a-f0a7-4fd6-872a-786808904dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>111,abc,XYz</value>
      <webElementGuid>18f14b13-7974-4b5a-8d71-a96612d4b1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serial_no&quot;)</value>
      <webElementGuid>9e0bc77f-2e75-4754-bdae-77a7adbf5361</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='serial_no']</value>
      <webElementGuid>a76392b0-a24c-4cb4-9bc0-6ad00be3f8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insert_product']/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>67eca354-5141-4431-a1ee-5e653ea3f12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>4f23457e-c695-4bed-8bf4-fc637f8f2dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'serial_no' and @name = 'serial_no' and @placeholder = '111,abc,XYz']</value>
      <webElementGuid>f09b10c5-55aa-4df6-a082-464b8d003098</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
