<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BarcodeQR-code_product_id</name>
   <tag></tag>
   <elementGuidId>75a21ebf-bb49-47d0-aef6-857498139f96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Barcode/QR-code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7f4244c-3813-4dfb-b470-cc8524b1b939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8e5ad457-6ea3-4d4b-aa32-4e1300645156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_id</value>
      <webElementGuid>9137bd76-e9ae-46b3-aff4-24adf8c5552a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e670f3c2-7bb0-4d71-910d-fb9266a38779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_id</value>
      <webElementGuid>4ab373b3-4d47-48d3-87d8-5f1e8621c573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Barcode/QR-code</value>
      <webElementGuid>848f7ab6-d2b5-4604-b571-bea3d3118f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4a926942-1706-4129-81b8-004f1e18f5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_id&quot;)</value>
      <webElementGuid>e228655e-dbf0-4ca1-89fd-c2dbaa36b3ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_id']</value>
      <webElementGuid>7191f378-4366-4ac8-a570-a2a40da55dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insert_product']/div/div/div/div/div/input</value>
      <webElementGuid>a31088d8-0d6e-4279-a256-35a1c597063b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d6d050f1-35ca-44cd-9c66-221db566d9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'product_id' and @type = 'text' and @id = 'product_id' and @placeholder = 'Barcode/QR-code']</value>
      <webElementGuid>ba7a3da8-09bf-4f3e-8f45-23cb3410a71b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
