<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select option_2</name>
   <tag></tag>
   <elementGuidId>16908164-06e8-4275-bf6c-d3c3185a590d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-supplier_id-tp-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-supplier_id-tp-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-supplier_id-tp-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>08b10121-0a93-43d2-97e9-144be5fbfb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>4e0eb9f8-ad36-4923-bb4c-6afb9d3a728a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-supplier_id-tp-container</value>
      <webElementGuid>6489a229-30c6-49fc-869f-659edba42c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select option</value>
      <webElementGuid>96d230c4-62a8-4324-9156-b20979e7374d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-supplier_id-tp-container&quot;)</value>
      <webElementGuid>9de618b0-c989-4aa4-a2ef-ff52f11049de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-supplier_id-tp-container']</value>
      <webElementGuid>d010e48c-0804-4b39-91c9-471313bea8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insert_product']/div/div[5]/div[3]/div/div/span/span/span/span</value>
      <webElementGuid>a7acc7df-6f66-42dd-8f4d-d31c3e67fac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[4]</value>
      <webElementGuid>3ce92f11-5b74-401f-a312-92927a8f473d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span/span/span/span</value>
      <webElementGuid>42bfa08e-15af-42ad-b1e6-b71c6694a20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-supplier_id-tp-container' and (text() = 'Select option' or . = 'Select option')]</value>
      <webElementGuid>5aa1239b-29bf-4c4b-b48b-bd112957b5ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
