#
testRail.password=uOvY0pj9KA/+lpTQmQ1JXK2w4MZBnWFO
testRail.isEncryptionMigrated=true
testRail.isTestRailEnabled=true
testRail.username="sayhoang.test@gmail.com"
testRail.url="https\://1757.testrail.io/"
testRail.project="2"
testRail.customFieldMappings="{}"
