<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__category_name</name>
   <tag></tag>
   <elementGuidId>374463ce-85c2-43d8-a934-626e1d6d3aa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Category Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a14b8eb-8687-426c-853a-f70fe988c07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db526ffa-614e-4c8a-ba42-4955261bd158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category_name</value>
      <webElementGuid>2fe0f581-c870-4c6c-b3a6-e730f01a3002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1c7f6b15-6817-4424-aea0-a4c9de8ae2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category_name</value>
      <webElementGuid>32633d15-4f16-459d-9d93-ea2e7f302af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Category Name</value>
      <webElementGuid>7ec69867-8f47-4c2c-823a-87c278fa556e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_name&quot;)</value>
      <webElementGuid>946e917a-0c04-4f0b-b723-29e5c466aa48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category_name']</value>
      <webElementGuid>2c698283-1dab-4a99-8d22-12b0ffe0f5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='category_form']/div/div/input</value>
      <webElementGuid>4b887a1c-c93d-4956-b5e2-28556b8cfc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>367a5a79-01fc-4e09-bc32-a81bba9c00c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'category_name' and @id = 'category_name' and @placeholder = 'Category Name']</value>
      <webElementGuid>276fe672-ade5-4be9-8a9b-70476679b749</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
