<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__category_name</name>
   <tag></tag>
   <elementGuidId>992e287e-4b4a-42c8-b6d7-e616125e0751</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Category Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10f0ef06-ed07-4814-b1af-a2f7bdf48a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>534da6cf-70df-4ce7-a3f4-23e973042776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category_name</value>
      <webElementGuid>c8555b67-f568-467b-a174-97f8f3dabb52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4ca41404-573c-4c37-95ec-213494af7b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category_name</value>
      <webElementGuid>d8d893aa-a3ee-47c9-8a91-a818b4a8d792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Category Name</value>
      <webElementGuid>79ade11a-5bda-41b9-a871-725b2ccbbae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_name&quot;)</value>
      <webElementGuid>8041ccf6-a0b7-49f1-9463-89ad6ddfef94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category_name']</value>
      <webElementGuid>9f9f6e0e-2fc1-4e25-8930-3360402d122c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='category_form']/div/div/input</value>
      <webElementGuid>d7a01d3b-d10f-416b-82be-9bf916e2dea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>52fab4ce-1f32-4f38-88af-f3287fce69f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'category_name' and @id = 'category_name' and @placeholder = 'Category Name']</value>
      <webElementGuid>2d2d24d5-9dd5-46ed-9c31-20314f5c676a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
